version: 2

project_name: zbbs

builds:
  - id: zbbs
    main: .
    dir: engine
    binary: zbbs
    ldflags:
      - -s -w
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: zbbs
    ids:
      - zbbs
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "zbbs_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^ci:'
      - '^chore:'
