package main

// Village event log (ZBBS-087). Player-facing feed of "things happening
// around town" — arrivals, departures, phase transitions. Distinct from
// agent_action_log (mechanical, includes private decisions) and from
// world_environment (chronicler atmosphere prose, fed to the top-bar
// marquee ticker). The Village tab on the talk_panel reads from here;
// the ticker reads from world_environment. They don't overlap by design.
//
// recordVillageEvent is the single write path: every event INSERTs and
// broadcasts in one place so we can't have a row land in the table
// without the WS event firing or vice versa.

import (
	"context"
	"encoding/json"
	"log"
	"net/http"
	"time"
)

// Event type constants. Match the CHECK constraint in the migration —
// adding a new type requires both the constraint and this list.
const (
	villageEventArrival     = "arrival"
	villageEventDeparture   = "departure"
	villageEventPhaseDawn   = "phase_dawn"
	villageEventPhaseMidday = "phase_midday"
	villageEventPhaseDusk   = "phase_dusk"
)

// villageEventRow is the wire-format payload used by both the WS event
// and the backload endpoint. JSON tags match snake_case the Godot client
// expects.
type villageEventRow struct {
	ID          int64    `json:"id"`
	EventType   string   `json:"event_type"`
	Text        string   `json:"text"`
	ActorID     *string  `json:"actor_id"`
	StructureID *string  `json:"structure_id"`
	X           *float64 `json:"x"`
	Y           *float64 `json:"y"`
	OccurredAt  string   `json:"occurred_at"`
}

// recordVillageEvent INSERTs a row and broadcasts village_event_added.
// Empty actorID / structureID become NULL. Pass nil for x or y when the
// event has no location (phase transitions). Errors are logged but not
// returned — village events are best-effort enrichment, not a critical
// path. A missed row is invisible; a missed broadcast just means the
// client backloads on next tab-open.
//
// Coordinates must be paired (both set or both nil) — the DB CHECK
// constraint enforces this so future visibility-radius filtering can
// rely on it. The helper guards in code too, with a log line so a bad
// caller is visible rather than producing a CHECK violation that
// silently fails the INSERT.
//
// occurred_at is generated by the DB (NOW(), via DEFAULT) and returned
// to the caller — keeps the event timestamp authoritative and avoids
// app/DB clock-skew ambiguity.
func (app *App) recordVillageEvent(ctx context.Context, eventType, text, actorID, structureID string, x, y *float64) {
	if (x == nil) != (y == nil) {
		log.Printf("village_event: %s passed partial coordinate (x=%v y=%v); dropping coords", eventType, x, y)
		x, y = nil, nil
	}

	var actorArg, structureArg, xArg, yArg interface{}
	if actorID != "" {
		actorArg = actorID
	}
	if structureID != "" {
		structureArg = structureID
	}
	if x != nil {
		xArg = *x
	}
	if y != nil {
		yArg = *y
	}

	var id int64
	var occurredAt time.Time
	err := app.DB.QueryRow(ctx,
		`INSERT INTO village_event (event_type, text, actor_id, structure_id, x, y)
		 VALUES ($1, $2, $3, $4, $5, $6)
		 RETURNING id, occurred_at`,
		eventType, text, actorArg, structureArg, xArg, yArg,
	).Scan(&id, &occurredAt)
	if err != nil {
		log.Printf("village_event: insert %s: %v", eventType, err)
		return
	}

	row := villageEventRow{
		ID:         id,
		EventType:  eventType,
		Text:       text,
		OccurredAt: occurredAt.Format(time.RFC3339Nano),
	}
	if actorID != "" {
		s := actorID
		row.ActorID = &s
	}
	if structureID != "" {
		s := structureID
		row.StructureID = &s
	}
	row.X = x
	row.Y = y

	app.Hub.Broadcast(WorldEvent{
		Type: "village_event_added",
		Data: row,
	})
}

// handleVillageLogRecent returns the most recent N village_event rows
// for backload when a client opens the Village tab. Default 50, max 200.
// Returned in chronological (oldest-first) order so the client can append
// without reversing — the recent-N selection happens in a subquery using
// the (occurred_at DESC, id DESC) index, and the outer SELECT flips back
// to ASC for display.
func (app *App) handleVillageLogRecent(w http.ResponseWriter, r *http.Request) {
	var req struct {
		Limit int `json:"limit"`
	}
	// Body is optional — empty body = default limit. Don't 400 on parse
	// failure; just use default.
	_ = json.NewDecoder(r.Body).Decode(&req)
	limit := req.Limit
	if limit <= 0 {
		limit = 50
	}
	if limit > 200 {
		limit = 200
	}

	rows, err := app.DB.Query(r.Context(),
		`SELECT id, event_type, text, actor_id, structure_id, x, y, occurred_at
		   FROM (
		       SELECT id, event_type, text, actor_id, structure_id, x, y, occurred_at
		         FROM village_event
		        ORDER BY occurred_at DESC, id DESC
		        LIMIT $1
		   ) recent
		  ORDER BY occurred_at ASC, id ASC`, limit,
	)
	if err != nil {
		jsonError(w, "Failed to load village log", http.StatusInternalServerError)
		return
	}
	defer rows.Close()

	out := make([]villageEventRow, 0, limit)
	for rows.Next() {
		var (
			row         villageEventRow
			actor, str  *string
			x, y        *float64
			occurredAt  time.Time
		)
		if err := rows.Scan(&row.ID, &row.EventType, &row.Text, &actor, &str, &x, &y, &occurredAt); err != nil {
			jsonError(w, "Failed to scan village log", http.StatusInternalServerError)
			return
		}
		row.ActorID = actor
		row.StructureID = str
		row.X = x
		row.Y = y
		row.OccurredAt = occurredAt.Format(time.RFC3339Nano)
		out = append(out, row)
	}
	if err := rows.Err(); err != nil {
		jsonError(w, "Failed to read village log", http.StatusInternalServerError)
		return
	}

	jsonResponse(w, http.StatusOK, map[string]any{"events": out})
}
