-- ZBBS-WORK-240: Slice 12 — Structures pg-impl.
--
-- Creates the v2 `structure` table (a building with interior rooms)
-- and reshapes the existing `structure_room` table to point at it.
-- Bundles dependent type changes on `actor` since this migration breaks
-- the referential-integrity FKs anyway (same Slice 11 precedent that
-- bundled actor.current_huddle_id retype with scene_huddle reshape).
--
-- Shared-Identity Bridge: a building is represented by BOTH a `structure`
-- row AND a `village_object` row that share the same UUID. This slice
-- enforces the bridge at migration time (every structure.id MUST equal
-- some village_object.id::text) and at the repo layer (SaveSnapshot
-- substrate guards). No schema-level FK between the two tables — that
-- would require retyping village_object.id from UUID to TEXT, a much
-- larger cross-aggregate ripple. Documented at
-- engine/sim/structure_anchors.go:14-23.
--
-- Backfill discriminator: any village_object referenced by
--   actor.{inside,home,work}_structure_id ∪ structure_room.structure_id
-- The structure_room union is load-bearing — without it, the new
-- structure_room→structure FK fails for legacy rooms whose structure has
-- no actor binding. (Caught by design_review pass 2026-05-19.)
--
-- Migration is NOT additive — it reshapes structure_room, drops FKs,
-- and retypes four columns on `actor`. After this migration:
--   * structure.id is TEXT (same value as village_object.id::text)
--   * structure_room.structure_id is TEXT, FK now points at structure(id)
--   * actor.{home,work,inside}_structure_id are TEXT NULL, no FK
--   * actor.inside_room_id stays BIGINT NULL but FK to structure_room dropped
--     (required so SaveSnapshot's stale-DELETE on structure CASCADEs through
--     structure_room without crashing into actor's NO-ACTION FK).
-- Slice 12 does NOT WRITE actor columns; Actors-pg-impl handles snapshot
-- of those values (which are preserved verbatim by the ::text cast).

BEGIN;

-- Step 1: Create `structure` table + sequence + indexes + CHECKs.
CREATE TABLE structure (
    id              TEXT PRIMARY KEY,
    display_name    TEXT NOT NULL,
    position_x      INT NOT NULL,
    position_y      INT NOT NULL,
    tags            TEXT[] NOT NULL DEFAULT '{}',
    leads_to_realm  TEXT NOT NULL DEFAULT '',
    snapshot_gen    BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT structure_id_nonempty           CHECK (btrim(id) <> ''),
    CONSTRAINT structure_display_name_nonempty CHECK (btrim(display_name) <> ''),
    CONSTRAINT structure_tags_no_nulls         CHECK (array_position(tags, NULL) IS NULL)
);

CREATE INDEX idx_structure_snapshot_gen ON structure(snapshot_gen);
CREATE SEQUENCE structure_snapshot_gen_seq START 1;

-- Step 2: Backfill from village_object rows that are structures.
--
-- Discriminator: referenced by any actor structure binding, or already
-- has a structure_room row. The structure_room union is load-bearing.
--
-- DisplayName fallback chain:
--   btrim(vo.display_name) → asset.name  (NOT NULL guarantees non-empty)
--
-- Position: tile coords floor-divided from pixel coords. 32 is v1's
-- pixel tile size (matches engine/sim/structure_anchors.go's WorldToTile).
-- Hard-coded here because migrations don't share constants with Go.

INSERT INTO structure (id, display_name, position_x, position_y, tags, leads_to_realm)
SELECT vo.id::text,
       COALESCE(NULLIF(btrim(vo.display_name), ''), a.name),
       FLOOR(vo.x / 32)::int,
       FLOOR(vo.y / 32)::int,
       COALESCE(vo.tags, '{}'),
       ''
  FROM village_object vo
  JOIN asset a ON a.id = vo.asset_id
 WHERE vo.id IN (
   SELECT inside_structure_id FROM actor WHERE inside_structure_id IS NOT NULL
   UNION SELECT home_structure_id   FROM actor WHERE home_structure_id   IS NOT NULL
   UNION SELECT work_structure_id   FROM actor WHERE work_structure_id   IS NOT NULL
   UNION SELECT structure_id        FROM structure_room WHERE structure_id IS NOT NULL
 )
ON CONFLICT (id) DO NOTHING;

-- Step 3: Validate strict bridge — fail loudly if any existing
-- structure_room row has no matching structure row. This catches any
-- gap in the backfill discriminator BEFORE we drop the old FK.
DO $$ DECLARE n_orphan int;
BEGIN
  SELECT COUNT(*) INTO n_orphan
    FROM structure_room sr
   WHERE NOT EXISTS (SELECT 1 FROM structure s WHERE s.id = sr.structure_id::text);
  IF n_orphan > 0 THEN
    RAISE EXCEPTION 'ZBBS-WORK-240: % structure_room rows reference no structure (expand backfill discriminator)', n_orphan;
  END IF;
END $$;

-- Step 4: Drop the old structure_room → village_object FK.
-- Constraint name is auto-generated by the original ZBBS-149 inline
-- REFERENCES; discover dynamically rather than hard-code.
DO $$ DECLARE c text;
BEGIN
  SELECT conname INTO c FROM pg_constraint
   WHERE conrelid = 'structure_room'::regclass
     AND contype = 'f'
     AND pg_get_constraintdef(oid) LIKE '%structure_id%REFERENCES%village_object%';
  IF c IS NOT NULL THEN EXECUTE format('ALTER TABLE structure_room DROP CONSTRAINT %I', c); END IF;
END $$;

-- Step 5: Retype structure_room.structure_id UUID → TEXT.
ALTER TABLE structure_room ALTER COLUMN structure_id TYPE TEXT USING structure_id::text;

-- Step 6: Add new FK structure_room.structure_id → structure(id) ON DELETE CASCADE.
-- Within-aggregate FK (StructuresRepo owns both tables); SaveSnapshot's
-- stale-DELETE on structure propagates to structure_room through this.
ALTER TABLE structure_room
    ADD CONSTRAINT structure_room_structure_id_fkey
    FOREIGN KEY (structure_id) REFERENCES structure(id) ON DELETE CASCADE;

-- Step 7: Add gen-marker + CHECKs on structure_room.
ALTER TABLE structure_room ADD COLUMN snapshot_gen BIGINT NOT NULL DEFAULT 0;
CREATE INDEX idx_structure_room_snapshot_gen ON structure_room(snapshot_gen);
CREATE SEQUENCE structure_room_snapshot_gen_seq START 1;

ALTER TABLE structure_room
    ADD CONSTRAINT structure_room_id_positive             CHECK (id > 0),
    ADD CONSTRAINT structure_room_structure_id_nonempty   CHECK (btrim(structure_id) <> ''),
    ADD CONSTRAINT structure_room_name_nonempty           CHECK (btrim(name) <> '');

-- Step 8: Drop actor.inside_room_id FK to structure_room.
-- Required so SaveSnapshot's stale-DELETE on structure CASCADEs through
-- structure_room without crashing into actor's NO-ACTION FK. Column
-- stays BIGINT NULL — soft ref same as Slice 11's actor.current_huddle_id.
DO $$ DECLARE c text;
BEGIN
  SELECT conname INTO c FROM pg_constraint
   WHERE conrelid = 'actor'::regclass
     AND contype = 'f'
     AND pg_get_constraintdef(oid) LIKE '%inside_room_id%REFERENCES%structure_room%';
  IF c IS NOT NULL THEN EXECUTE format('ALTER TABLE actor DROP CONSTRAINT %I', c); END IF;
END $$;

-- Step 9: Drop the three actor → village_object FKs (auto-named per
-- inline REFERENCES in ZBBS-084) and retype the columns to TEXT.
-- UUID→TEXT cast is lossless; values continue pointing at correct
-- structures via the shared-identity bridge (same string keys).
-- Slice 12 does NOT WRITE these columns; Actors-pg-impl will.
DO $$ DECLARE c text;
BEGIN
  FOR c IN
    SELECT conname FROM pg_constraint
     WHERE conrelid = 'actor'::regclass
       AND contype = 'f'
       AND pg_get_constraintdef(oid) ~ '(home|work|inside)_structure_id.*REFERENCES.*village_object'
  LOOP
    EXECUTE format('ALTER TABLE actor DROP CONSTRAINT %I', c);
  END LOOP;
END $$;

ALTER TABLE actor ALTER COLUMN home_structure_id   TYPE TEXT USING home_structure_id::text;
ALTER TABLE actor ALTER COLUMN work_structure_id   TYPE TEXT USING work_structure_id::text;
ALTER TABLE actor ALTER COLUMN inside_structure_id TYPE TEXT USING inside_structure_id::text;

COMMIT;
